-- 1️. Customer Insights
-- How many unique customers have placed orders?
use grocery;
select count(distinct cust_id) as unique_cust from customers;

-- Which customers have placed the highest number of orders?
select o.cust_id,c.cust_name, count(*) as total_cust
from orders o 
join customers c on
o.cust_id=c.cust_id
group by cust_id
order by total_cust desc;

-- What is the total and average purchase value per customer?
select o.cust_id,c.cust_name, sum(total_price) as total_pur, avg(total_price) as avg_pur
from orders o
join customers c
on c.cust_id=o.cust_id
join order_details od
on o.ord_id=od.ord_id
group by o.cust_id;

-- Who are the top 5 customers by total purchase amount?
select o.cust_id,c.cust_name, sum(total_price) as total_pur
from orders o
join customers c
on c.cust_id=o.cust_id
join order_details od
on o.ord_id=od.ord_id
group by o.cust_id
order by total_pur desc
limit 6;

-- 2. Product Performance
-- How many products exist in each category?
select * from categories;
select * from products;
select p.cat_id,count(p.prod_name) as each_product
from products p
group by p.cat_id;

-- What is the average price of products by category?
select p.cat_id ,c.cat_name, avg(price) as avg_prz
from products p
join categories c
on p.cat_id=c.cat_id
group by cat_id;

-- Which products have the highest total sales volume (by quantity)?
select od.prod_id,p.prod_name, sum(quantity) as total_sales 
from order_details od
join products p
on p.prod_id=od.prod_id
group by od.prod_id
order by total_sales desc;

-- What is the total revenue generated by each product?
select prod_id, sum(total_price) as total_rev
from order_details
group by prod_id;

-- How do product sales vary by category and supplier?
select p.sup_id,p.cat_id,
sum(od.quantity) as total_unit_sold,
sum(od.total_price) as total_sales
from order_details od
join products p on 
p.prod_id=od.prod_id
group by p.sup_id,p.cat_id
order by total_sales desc;

-- 3. Sales and Order Trends
-- How many orders have been placed in total?
select count(ord_id) as no_oforders from orders;
 
 -- What is the average value per order?
select ord_id, avg(total_price) as avg_value 
from order_details
group by ord_id;

-- On which dates were the most orders placed?
select order_date,count(ord_id) as most_orders
from orders
group by order_date
having count(ord_id)=(
select max(order_count)
from(select count(ord_id) as order_count
from orders
group by order_date)t
);

-- What are the monthly trends in order volume and revenue?
SELECT 
    MONTH(o.order_date) AS month,
    COUNT(o.ord_id) AS total_orders,
    SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od
    ON o.ord_id = od.ord_id
GROUP BY MONTH(order_date)
ORDER BY month;

-- How do order patterns vary across weekdays and weekends?
SELECT 
    DAYNAME(order_date) AS day,
    COUNT(ord_id) AS total_orders
FROM orders
GROUP BY DAYNAME(order_date);

select * from orders;

alter table orders
modify column order_date date;

UPDATE orders
SET order_date = STR_TO_DATE(order_date, '%m/%d/%Y');

desc orders;

-- 4️. Supplier Contribution
-- How many suppliers are there in the database?
select count(sup_id) from supplier;

-- Which supplier provides the most products?
select s.sup_name,p.sup_id, count(p.prod_id) as high_supplier
from products p
join supplier s on
s.sup_id=p.sup_id
group by p.sup_id
order by high_supplier desc
limit 1;

-- What is the average price of products from each supplier?
select s.sup_name, p.sup_id, avg(p.price) as sup_avg_price
from products p
join supplier s on
s.sup_id=p.sup_id
group by p.sup_id;

select * from products;
-- Which suppliers contribute the most to total product sales (by revenue)
select s.sup_name,p.sup_id,sum(od.total_price) as high_revenue_sup
from products p
join supplier s on
s.sup_id=p.sup_id
join order_details od
on p.prod_id -od.prod_id
group by p.sup_id
order by high_revenue_sup desc;

-- 5️. Employee Performance
-- How many employees have processed orders?
select count(emp_id) from employees;

-- Which employees have handled the most orders?
select o.emp_id ,e.emp_name, count(o.ord_id) as most_orders
from orders o
join employees e on
o.emp_id=e.emp_id
group by emp_id
order by most_orders desc
limit 1;

-- What is the total sales value processed by each employee?
select o.emp_id ,e.emp_name, sum(od.total_price) as total_sales
from orders o
join employees e on 
e.emp_id=o.emp_id
join order_details od on
o.ord_id=o.ord_id
group by o.emp_id
order by total_sales desc;
 
-- What is the average order value handled per employee?

SELECT o.emp_id,e.emp_name,
       AVG(od.total_price) AS avg_order_value
FROM orders o
join employees e on 
e.emp_id=o.emp_id
JOIN order_details od
    ON o.ord_id = od.ord_id
GROUP BY o.emp_id; 

-- 6️. Order Details Deep Dive
-- What is the relationship between quantity ordered and total price?
select * from order_details;
select quantity, total_price from order_details;

-- What is the average quantity ordered per product?
select od.prod_id,p.prod_name, avg(od.quantity) as avg_quant
from order_details od
join products p on 
od.prod_id=p.prod_id
group by od.prod_id;

-- How does the unit price vary across products and orders?
SELECT od.prod_id,p.prod_name,
       AVG(each_price) AS avg_unit_price,
       MIN(each_price) AS min_unit_price,
       MAX(each_price) AS max_unit_price
FROM order_details od
join products p on 
od.prod_id=p.prod_id
GROUP BY od.prod_id;


-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);








